import { createContext, useContext, useState, useCallback, useMemo } from 'react';

const LanguageContext = createContext(null);
export const useLanguage = () => useContext(LanguageContext);

const translations = {
  de: {
    // Navigation
    'nav.today': 'Heute',
    'nav.growth': 'Wachstum',
    'nav.insights': 'Insights',
    'nav.commandCenter': 'Dashboard',
    'nav.dailyCheckin': 'Täglicher Check-in',
    'nav.tasks': 'Aufgaben',
    'nav.aiCoach': 'WladBot',
    'nav.simulations': 'Simulationen',
    'nav.challengers': 'Challengers',
    'nav.playbooks': 'Playbooks',
    'nav.missions': 'Video Analyse',
    'nav.workflows': 'Workflows',
    'nav.progress': 'Fortschritt',
    'nav.events': 'Events',
    'nav.coaching': 'Coaching',
    'nav.darkMode': 'Dark Mode',
    'nav.lightMode': 'Light Mode',
    'nav.logout': 'Abmelden',
    'nav.diagnostic': 'Diagnose',

    // Dashboard
    'dash.goodMorning': 'Guten Morgen',
    'dash.goodAfternoon': 'Guten Tag',
    'dash.goodEvening': 'Guten Abend',
    'dash.leaderScore': 'Leader Score',
    'dash.dayStreak': 'Tage Streak',
    'dash.checkedIn': 'Heute eingecheckt',
    'dash.checkedInSub': 'Weiter so! Halte dein Momentum.',
    'dash.notCheckedIn': 'Starte deinen Tag mit einem Leadership Check-in.',
    'dash.whatMatters': 'Was heute zählt',
    'dash.nextLevel': 'Dein nächstes Level',
    'dash.quickActions': 'Schnellzugriff',
    'dash.weeklyActivity': 'Wochenaktivität',
    'dash.viewAll': 'Alle anzeigen',
    'dash.tasksDone': 'Aufgaben erledigt',
    'dash.simulations': 'Simulationen',
    'dash.totalXp': 'Gesamt XP',
    'dash.unlockCoaching': 'Premium Leadership Coaching mit Wlad',
    'dash.unlockCoachingSub': 'Persönliche 1:1 Sessions, VIP-Zugang zu allen Trainings und dein individueller Entwicklungsplan.',
    'dash.learnMore': 'Mehr erfahren',

    // Check-in - Enhanced with Wlad Jachtchenko Frameworks
    'checkin.title': 'Täglicher Leadership Check-in',
    'checkin.subtitle': 'Teile dein Leadership-Moment. Erhalte sofortiges KI-Feedback basierend auf bewährten Frameworks.',
    'checkin.placeholder': 'Beschreibe eine Führungssituation: eine Entscheidung, ein Gespräch, eine Herausforderung oder einen Erfolg von heute...',
    'checkin.orVoice': 'oder per Sprache',
    'checkin.submit': 'Analysieren',
    'checkin.update': 'Aktualisieren',
    'checkin.analyzing': 'Analysiere...',
    'checkin.todayComplete': 'Heutiger Check-in abgeschlossen',
    'checkin.aiFeedback': 'KI-Feedback',
    'checkin.tipTomorrow': 'Tipp für Morgen',
    'checkin.impact': 'Impact',
    'checkin.recent': 'Letzte Check-ins',
    'checkin.prompts': [
      'Wlad sagt: "Die Qualität deiner Führung zeigt sich in der Qualität deiner Gespräche." · Welches Gespräch hat dich heute herausgefordert?',
      'Framework "Feedbackformel": Beobachtung + Wirkung + Wunsch · Hast du heute Feedback gegeben oder erhalten?',
      'Wlad: "Delegation ist kein Abgeben, sondern Befähigen." · Was hast du heute delegiert?',
      'Die 3 Säulen der Überzeugung: Logos, Ethos, Pathos · Musstest du heute jemanden überzeugen?',
      'Wlad: "Ein Leader entscheidet. Nicht-Entscheiden ist die schlechteste Entscheidung." · Welche Entscheidung stand heute an?',
      'Aktives Zuhören: Paraphrasieren, Emotionen benennen, nachfragen · Wie gut hast du heute zugehört?',
    ],

    // Chat
    'chat.title': 'KI Leadership Coach',
    'chat.subtitle': 'Wähle deinen Spezialisten-Agenten',
    'chat.newChat': 'Neuer Chat',
    'chat.placeholder': 'Beschreibe deine Leadership-Herausforderung...',
    'chat.emptyTitle': 'Dein persönlicher Leadership Coach',
    'chat.emptySub': 'Wähle oben einen Agenten, oder frag mich einfach.',
    'chat.quickPrompts': [
      'Hilf mir, ein schwieriges 1:1 vorzubereiten',
      'Feedback an einen Underperformer geben',
      'Teamkonflikt lösen',
      'Effektiv delegieren',
      'Schwierige Einstellungsentscheidung treffen',
      'Ich fühle mich als Leader blockiert',
    ],
    'chat.scenarios': 'Typische Szenarien',

    // Simulations
    'sim.title': 'Leadership Simulationen',
    'sim.subtitle': 'Übe echte Gespräche. Nutze Sprache oder Text. Werde bewertet.',
    'sim.arena': 'Leadership Training Arena',
    'sim.arenaSub': 'Übe reale Szenarien mit KI. Nutze deine Stimme für ein realistisches Erlebnis.',
    'sim.live': 'LIVE SIMULATION',
    'sim.liveSub': 'Antworte natürlich. Nutze Sprache oder Text. Die KI reagiert dynamisch.',
    'sim.endSim': 'Simulation beenden',
    'sim.complete': 'Simulation abgeschlossen',
    'sim.completeSub': 'Hier ist deine personalisierte Leistungsanalyse',
    'sim.downloadReport': 'Vollständigen Report herunterladen',
    'sim.fasterGrowth': '3x schneller wachsen?',
    'sim.fasterGrowthSub': 'Erhalte personalisiertes 1:1 Coaching basierend auf deinen Ergebnissen',

    // Missions
    'mission.title': 'Leadership Missionen',
    'mission.subtitle': 'Nimm dich auf bei harten Szenarien. KI bewertet deine Lieferung. Schlage deinen letzten Score.',
    'mission.start': 'Mission starten',
    'mission.recording': 'AUFNAHME',
    'mission.startRec': 'Aufnahme starten',
    'mission.stopRec': 'Aufnahme stoppen',
    'mission.reRecord': 'Nochmal aufnehmen',
    'mission.submitAnalysis': 'Zur Analyse einreichen',
    'mission.analyzing': 'Analysiere deine Leadership-Lieferung...',
    'mission.analyzingSub': 'Bewerte Klarheit, Selbstbewusstsein, Empathie & Struktur',
    'mission.complete': 'MISSION ABGESCHLOSSEN',
    'mission.results': 'Ergebnisse',
    'mission.resultsSub': 'Hier ist deine personalisierte Performance-Analyse',
    'mission.transcript': 'Dein Transkript',
    'mission.feedback': 'KI-Feedback',
    'mission.strengths': 'Stärken',
    'mission.improvements': 'Verbesserungspotenzial',
    'mission.rewrite': 'Vorgeschlagene Umformulierung',
    'mission.downloadReport': 'Vollständigen Missions-Report herunterladen',
    'mission.backToMissions': 'Zurück zu Missionen',
    'mission.cancel': 'Abbrechen',

    // Workflows
    'wf.title': 'Geführte Workflows',
    'wf.subtitle': 'Schritt-für-Schritt KI-Workflows. Beantworte Fragen. Erhalte personalisierte Ergebnisse.',
    'wf.steps': 'Schritte',
    'wf.step': 'Schritt',
    'wf.of': 'von',
    'wf.previous': 'Zurück',
    'wf.next': 'Weiter',
    'wf.generateResults': 'Ergebnisse generieren',
    'wf.analyzing': 'Analysiere dein Leadership-Muster...',
    'wf.analyzingSub': 'Erstelle deinen personalisierten Workflow',
    'wf.complete': 'WORKFLOW ABGESCHLOSSEN',
    'wf.downloadReport': 'Vollständigen Report herunterladen',
    'wf.back': 'Zurück',

    // Playbooks
    'pb.title': 'Leadership Playbooks',
    'pb.subtitle': 'Interaktive Kurse mit WladBot als Coach. Lerne durch Gespräche.',
    'pb.start': 'Starten',
    'pb.continue': 'Fortsetzen',
    'pb.step': 'Schritt',
    'pb.generateReport': 'Persönlichen Report generieren',
    'pb.generatingReport': 'Generiere deinen Report...',
    'pb.downloadReport': 'Report herunterladen',

    // Reports
    'report.generating': 'Generiere deinen personalisierten Report...',
    'report.analyzingData': 'Analysiere deine Daten',
    'report.buildingInsights': 'Erstelle Erkenntnisse',
    'report.personalizingPlan': 'Personalisiere Aktionsplan',
    'report.finalizing': 'Finalisiere Report',

    // Upsell - Enhanced with Wlad Jachtchenko
    'upsell.title': 'Premium Leadership Programm mit Wlads Team',
    'upsell.subtitle': 'Erhalte personalisiertes 1:1 Coaching von Wlads Team, erweiterte KI-Simulationen und deinen kompletten Leadership-Transformationsplan.',
    'upsell.cta': 'Transformation starten',
    'upsell.noCreditCard': 'Strategiegespräch buchen',
    'upsell.features': [
      'Persönliche 1:1 Coaching Sessions mit Wlads Team',
      'Alle Frameworks aus "Die Kunst der Überzeugung"',
      'Erweiterte KI-Simulationen & Analyse',
      'Lebenslanger Zugang zu allen Premium-Features',
      'Exklusiver Zugang zur Leader-Community',
      'Monatlicher Fortschritts-Report',
    ],
    'upsell.bookCall': 'Persönliches Strategiegespräch buchen',
    'upsell.bookCallSub': '15 Min · 1:1 mit Wlads Team · unverbindlich',

    // Funnel / Diagnostic
    'funnel.heroTitle': 'Dein Leadership-Profil in 10 Minuten.',
    'funnel.heroSub': 'Entdecke, welche Führungsrolle dich definiert.',
    'funnel.startBtn': 'Kostenlose Leadership-Diagnose starten',
    'funnel.startSub': '10 Minuten · Sofortiger Report · Persönlicher Aktionsplan',
    'funnel.q1': 'In welcher Rolle bist du tätig?',
    'funnel.q1opts': ['Selbstständig / Gründer', 'Teamleiter / Manager', 'Senior Manager / Director', 'C-Level / Vorstand', 'High Potential / Aufsteiger', 'Andere'],
    'funnel.q2': 'Was ist deine größte Herausforderung als Führungskraft?',
    'funnel.q2opts': ['Schwierige Gespräche führen', 'Strategische Entscheidungen treffen', 'Team motivieren & binden', 'KI im Führungsalltag nutzen', 'Delegation & Loslassen', 'Sichtbarkeit & Überzeugungskraft'],
    'funnel.q3': 'Wie gut nutzt du KI bereits als Führungskraft?',
    'funnel.q3opts': ['Gar nicht · ich weiß nicht, wo ich anfangen soll', 'Grundlagen · ich nutze ChatGPT gelegentlich', 'Fortgeschritten · KI ist Teil meiner Workflows', 'Profi · ich integriere KI strategisch'],
    'funnel.q4': 'Was beschreibt deinen Kommunikationsstil am besten?',
    'funnel.q4opts': ['Direkt & sachlich', 'Diplomatisch & empathisch', 'Inspirierend & visionär', 'Analytisch & datengetrieben'],
    'funnel.q5': 'Was ist dein wichtigstes Ziel in den nächsten 90 Tagen?',
    'funnel.q5placeholder': 'z.B. "Ich möchte mein Team besser führen und KI strategisch einsetzen..."',

    // Common
    'common.leadership': 'Leadership',
    'common.eq': 'EQ',
    'common.communication': 'Kommunikation',
    'common.overall': 'Gesamt',
    'common.clarity': 'Klarheit',
    'common.confidence': 'Selbstvertrauen',
    'common.empathy': 'Empathie',
    'common.structure': 'Struktur',
    'common.strengths': 'Stärken',
    'common.improvements': 'Verbesserungspotenzial',
    'common.download': 'Herunterladen',
    'common.cancel': 'Abbrechen',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.submit': 'Absenden',
    'common.loading': 'Laden...',

    // Events
    'events.title': 'Leadership Events',
    'events.subtitle': 'Webinare, Workshops & Trainings für deinen Aufstieg',
    'events.all': 'Alle Events',
    'events.featured': 'Highlights',
    'events.registerFree': 'Kostenlos anmelden',
    'events.registering': 'Wird angemeldet...',
    'events.register': 'Anmelden',
    'events.spotsLeft': 'Plätze frei',

    // Login
    'login.welcome': 'Willkommen',
    'login.subtitle': 'Melde dich an, um auf dein Leadership Dashboard zuzugreifen',
    'login.signIn': 'Anmelden',
    'login.signUp': 'Registrieren',
    'login.email': 'E-Mail',
    'login.password': 'Passwort',
    'login.name': 'Vollständiger Name',
    'login.signingIn': 'Wird angemeldet...',
    'login.creatingAccount': 'Konto wird erstellt...',
    'login.createAccount': 'Konto erstellen',
    'login.orContinue': 'oder fortfahren mit',
    'login.google': 'Mit Google fortfahren',
  },
  en: {
    'nav.today': 'Today',
    'nav.growth': 'Growth',
    'nav.insights': 'Insights',
    'nav.commandCenter': 'Command Center',
    'nav.dailyCheckin': 'Daily Check-in',
    'nav.tasks': 'Tasks',
    'nav.aiCoach': 'WladBot',
    'nav.simulations': 'Simulations',
    'nav.challengers': 'Challengers',
    'nav.playbooks': 'Playbooks',
    'nav.missions': 'Video Analysis',
    'nav.workflows': 'Workflows',
    'nav.progress': 'Progress',
    'nav.events': 'Events',
    'nav.coaching': 'Coaching',
    'nav.darkMode': 'Dark Mode',
    'nav.lightMode': 'Light Mode',
    'nav.logout': 'Logout',
    'nav.diagnostic': 'Diagnostic',
    'dash.goodMorning': 'Good morning',
    'dash.goodAfternoon': 'Good afternoon',
    'dash.goodEvening': 'Good evening',
    'dash.leaderScore': 'Leader Score',
    'dash.dayStreak': 'day streak',
    'dash.checkedIn': 'Checked in today',
    'dash.checkedInSub': 'Keep the momentum going.',
    'dash.notCheckedIn': 'Start your day with a leadership check-in.',
    'dash.whatMatters': 'What Matters Today',
    'dash.nextLevel': 'Your Next Level',
    'dash.quickActions': 'Quick Actions',
    'dash.weeklyActivity': 'Weekly Activity',
    'dash.viewAll': 'View All',
    'dash.tasksDone': 'Tasks Done',
    'dash.simulations': 'Simulations',
    'dash.totalXp': 'Total XP',
    'dash.unlockCoaching': 'Unlock 1:1 Leadership Coaching',
    'dash.unlockCoachingSub': 'Complete leadership transformation with personal expert guidance.',
    'dash.learnMore': 'Learn More',
    'checkin.title': 'Daily Leadership Check-in',
    'checkin.subtitle': 'Log your leadership moment. Get instant AI feedback.',
    'checkin.placeholder': 'Share your leadership moment...',
    'checkin.orVoice': 'or use voice',
    'checkin.submit': 'Submit Check-in',
    'checkin.update': 'Update',
    'checkin.analyzing': 'Analyzing...',
    'checkin.todayComplete': "Today's check-in complete",
    'checkin.aiFeedback': 'AI Feedback',
    'checkin.tipTomorrow': 'Tip for Tomorrow',
    'checkin.impact': 'Impact',
    'checkin.recent': 'Recent Check-ins',
    'checkin.prompts': [
      'What leadership decision did you make today?',
      'Describe a conversation that challenged you today.',
      'What did you delegate today and how did it go?',
      'How did you handle a conflict or disagreement?',
      'What feedback did you give or receive today?',
      'What was your biggest leadership win today?',
    ],
    'chat.title': 'AI Leadership Coach',
    'chat.subtitle': 'Choose your specialist agent below',
    'chat.newChat': 'New Chat',
    'chat.placeholder': 'Describe your leadership challenge...',
    'chat.emptyTitle': 'Your Personal Leadership Coach',
    'chat.emptySub': 'Select an agent above, or ask me anything about leadership.',
    'chat.quickPrompts': ['Help me prepare a difficult 1:1', 'Give feedback to underperformer', 'Handle team conflict', 'Delegate effectively', 'Make a tough hiring decision', 'I feel stuck as a leader'],
    'chat.scenarios': 'Common Scenarios',
    'sim.title': 'Leadership Simulations',
    'sim.subtitle': 'Practice real conversations. Use voice or text. Get scored.',
    'sim.arena': 'Leadership Training Arena',
    'sim.arenaSub': 'Practice real-world scenarios with AI. Use your voice for a realistic experience.',
    'sim.live': 'LIVE SIMULATION',
    'sim.liveSub': 'Respond naturally. Use voice or text. The AI reacts dynamically.',
    'sim.endSim': 'End Simulation',
    'sim.complete': 'Simulation Complete',
    'sim.completeSub': "Here's your personalized performance report",
    'sim.downloadReport': 'Download Full Report',
    'sim.fasterGrowth': 'Want to improve 3x faster?',
    'sim.fasterGrowthSub': 'Get personalized 1:1 coaching based on your results',
    'mission.title': 'Leadership Missions',
    'mission.subtitle': 'Record yourself tackling tough scenarios. AI scores your delivery. Beat your last score.',
    'mission.start': 'Start Mission',
    'mission.recording': 'RECORDING',
    'mission.startRec': 'Start Recording',
    'mission.stopRec': 'Stop Recording',
    'mission.reRecord': 'Re-record',
    'mission.submitAnalysis': 'Submit for Analysis',
    'mission.analyzing': 'Analyzing your leadership delivery...',
    'mission.analyzingSub': 'Evaluating clarity, confidence, empathy & structure',
    'mission.complete': 'MISSION COMPLETE',
    'mission.results': 'Results',
    'mission.resultsSub': "Here's your personalized performance analysis",
    'mission.transcript': 'Your Transcript',
    'mission.feedback': 'AI Feedback',
    'mission.strengths': 'Strengths',
    'mission.improvements': 'Areas to Improve',
    'mission.rewrite': 'Suggested Rewrite',
    'mission.downloadReport': 'Download Full Mission Report',
    'mission.backToMissions': 'Back to Missions',
    'mission.cancel': 'Cancel',
    'wf.title': 'Guided Workflows',
    'wf.subtitle': 'Step-by-step AI workflows. Answer questions. Get personalized results.',
    'wf.steps': 'steps',
    'wf.step': 'Step',
    'wf.of': 'of',
    'wf.previous': 'Previous',
    'wf.next': 'Next',
    'wf.generateResults': 'Generate Results',
    'wf.analyzing': 'Analyzing your leadership pattern...',
    'wf.analyzingSub': 'Creating your personalized workflow',
    'wf.complete': 'WORKFLOW COMPLETE',
    'wf.downloadReport': 'Download Full Report',
    'wf.back': 'Back',
    'pb.title': 'Leadership Playbooks',
    'pb.subtitle': 'Interactive courses with WladBot as your coach. Learn through conversation.',
    'pb.start': 'Start',
    'pb.continue': 'Continue',
    'pb.step': 'Step',
    'pb.generateReport': 'Generate Personal Report',
    'pb.generatingReport': 'Generating your report...',
    'pb.downloadReport': 'Download Report',
    'report.generating': 'Generating your personalized report...',
    'report.analyzingData': 'Analyzing your data',
    'report.buildingInsights': 'Building insights',
    'report.personalizingPlan': 'Personalizing action plan',
    'report.finalizing': 'Finalizing report',
    'upsell.title': 'Unlock Your Full Leadership Potential',
    'upsell.subtitle': 'Get personalized 1:1 coaching, advanced AI simulations, and your complete leadership transformation plan.',
    'upsell.cta': 'Start Your Transformation',
    'upsell.noCreditCard': 'Book a strategy call',
    'upsell.features': ['Personalized 1:1 Executive Coaching', 'Complete Leadership Transformation Program', 'Advanced AI Simulations & Analysis', 'Lifetime Access to All Premium Features', 'Priority Support & Community Access'],
    'funnel.heroTitle': 'Your Leadership Profile in 10 Minutes.',
    'funnel.heroSub': 'Discover which leadership role defines you.',
    'funnel.startBtn': 'Start Leadership Diagnostic',
    'funnel.startSub': '10 minutes · Instant report · Personal action plan',
    'funnel.q1': 'What is your current role?',
    'funnel.q1opts': ['Self-employed / Founder', 'Team Lead / Manager', 'Senior Manager / Director', 'C-Level / Executive', 'High Potential / Rising Star', 'Other'],
    'funnel.q2': 'What is your biggest leadership challenge?',
    'funnel.q2opts': ['Having difficult conversations', 'Making strategic decisions', 'Motivating & retaining team', 'Using AI in leadership', 'Delegation & letting go', 'Visibility & persuasion'],
    'funnel.q3': 'How well do you use AI as a leader?',
    'funnel.q3opts': ["Not at all · I don't know where to start", "Basics · I use ChatGPT occasionally", 'Advanced · AI is part of my workflows', 'Pro · I integrate AI strategically'],
    'funnel.q4': 'What best describes your communication style?',
    'funnel.q4opts': ['Direct & factual', 'Diplomatic & empathetic', 'Inspiring & visionary', 'Analytical & data-driven'],
    'funnel.q5': 'What is your most important goal in the next 90 days?',
    'funnel.q5placeholder': 'e.g. "I want to lead my team better and integrate AI strategically..."',
    'common.leadership': 'Leadership',
    'common.eq': 'EQ',
    'common.communication': 'Communication',
    'common.overall': 'Overall',
    'common.clarity': 'Clarity',
    'common.confidence': 'Confidence',
    'common.empathy': 'Empathy',
    'common.structure': 'Structure',
    'common.strengths': 'Strengths',
    'common.improvements': 'Areas to Improve',
    'common.download': 'Download',
    'common.cancel': 'Cancel',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.submit': 'Submit',
    'common.loading': 'Loading...',

    // Events
    'events.title': 'Leadership Events',
    'events.subtitle': 'Webinars, Workshops & Trainings for your growth',
    'events.all': 'All Events',
    'events.featured': 'Featured',
    'events.registerFree': 'Register Free',
    'events.registering': 'Registering...',
    'events.register': 'Register',
    'events.spotsLeft': 'spots left',

    // Login
    'login.welcome': 'Welcome',
    'login.subtitle': 'Sign in to access your leadership dashboard',
    'login.signIn': 'Sign In',
    'login.signUp': 'Sign Up',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.name': 'Full Name',
    'login.signingIn': 'Signing in...',
    'login.creatingAccount': 'Creating account...',
    'login.createAccount': 'Create Account',
    'login.orContinue': 'or continue with',
    'login.google': 'Continue with Google',
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => sessionStorage.getItem('wladbot_lang') || 'de');

  const toggleLang = useCallback(() => {
    setLang(prev => {
      const next = prev === 'de' ? 'en' : 'de';
      sessionStorage.setItem('wladbot_lang', next);
      return next;
    });
  }, []);

  const t = useCallback((key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  }, [lang]);

  const value = useMemo(() => ({ lang, toggleLang, t }), [lang, toggleLang, t]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
